export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpg",
    username: "Joe Smith",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpg",
    username: "Clara Johnson",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpg",
    username: "Sam Jordan",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpg",
    username: "Smith Jonas",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpg",
    username: "Emma Williams",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Liam Brown",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpg",
    username: "Olivia Davis",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Noah Miller",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Ava Wilson",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Isabella Taylor",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for All, Hatred for None",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Stay positive, work hard, make it happen",
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 45,
    comment: 12,
  },
  {
    id: 3,
    desc: "Believe you can and you're halfway there",
    photo: "assets/post/3.jpg",
    date: "30 mins ago",
    userId: 3,
    like: 50,
    comment: 14,
  },
  {
    id: 4,
    desc: "Be the change you wish to see in the world",
    photo: "assets/post/4.jpg",
    date: "1 hour ago",
    userId: 4,
    like: 65,
    comment: 20,
  },
  {
    id: 5,
    desc: "The only limit to our realization of tomorrow is our doubts of today",
    photo: "assets/post/5.jpg",
    date: "2 hours ago",
    userId: 5,
    like: 70,
    comment: 25,
  },
  {
    id: 6,
    desc: "Do not wait to strike till the iron is hot; but make it hot by striking",
    photo: "assets/post/6.jpg",
    date: "3 hours ago",
    userId: 6,
    like: 80,
    comment: 30,
  },
  {
    id: 7,
    desc: "It always seems impossible until it’s done",
    photo: "assets/post/7.jpg",
    date: "5 hours ago",
    userId: 7,
    like: 85,
    comment: 35,
  },
  {
    id: 8,
    desc: "Success is not the key to happiness. Happiness is the key to success",
    photo: "assets/post/8.jpg",
    date: "8 hours ago",
    userId: 8,
    like: 90,
    comment: 40,
  },
  {
    id: 9,
    desc: "The best way to predict the future is to create it",
    photo: "assets/post/9.jpg",
    date: "10 hours ago",
    userId: 9,
    like: 95,
    comment: 45,
  },
  {
    id: 10,
    desc: "Do what you can with all you have, wherever you are",
    photo: "assets/post/10.jpg",
    date: "12 hours ago",
    userId: 10,
    like: 100,
    comment: 50,
  },
  {
    id: 11,
    desc: "You are never too old to set another goal or to dream a new dream",
    photo: "assets/post/11.jpg",
    date: "1 day ago",
    userId: 1,
    like: 110,
    comment: 55,
  },
  {
    id: 12,
    desc: "Act as if what you do makes a difference. It does",
    photo: "assets/post/12.jpg",
    date: "2 days ago",
    userId: 2,
    like: 120,
    comment: 60,
  },
];
